# -*- coding: utf-8 -*-
"""jump_the_tiles

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WVo9j7k4Dsq34nan-cbYSUtTztwYuVLu
"""

board = [
 [2, 1, 2, 1, 1, 2, 3, 1, 3, 3],
 [3, 3, 3, 2, 3, 3, 3, 2, 3, 3],
 [2, 1, 3, 3, 2, 2, 3, 3, 2, 3],
 [1, 2, 1, 1, 3, 1, 3, 2, 2, 3],
 [1, 2, 2, 2, 2, 1, 2, 1, 2, 2],
 [1, 2, 3, 2, 3, 2, 1, 2, 3, 1],
 [1, 2, 2, 3, 3, 2, 3, 3, 1, 1],
 [3, 2, 1, 2, 1, 2, 1, 3, 3, 2],
 [2, 3, 2, 3, 1, 3, 2, 2, 1, 2],
 [2, 1, 3, 3, 1, 3, 1, 1, 2, 2]
]

class Coordinates:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def get_x(self):
        return self.x
    def get_y(self):
        return self.y

marker = Coordinates(4,4)
goal = Coordinates(3,4)

def print_board(board):
    print("*"*20)
    x0 = marker.x
    y0 = marker.y
    x1 = goal.x
    y1 = goal.y
    for x in range(len(board)):
        for y in range(len(board[x])):
            if(x == x0 and y == y0):
                print(0," ", end='') #start tile
            elif(x == x1 and y == y1):
                print(9," ", end='') #goal tile
            else:
                print(board[x][y], " ", end='')
        print()
    print("*"*20)

def move_marker(board,marker,d): #d denotes the direction (0-7)
    dir = {
        0:Coordinates(0,1),
        1:Coordinates(-1,1),
        2:Coordinates(-1,0),
        3:Coordinates(-1,-1),
        4:Coordinates(0,-1),
        5:Coordinates(1,-1),
        6:Coordinates(1,0),
        7:Coordinates(1,1)
    }
    x1 = marker.x
    y1 = marker.y
    j = board[x1][y1] #can only jump j steps i.e. the number at which marker is

    marker = Coordinates(x1+dir[d].x*j, y1+dir[d].y*j)
    return marker

#play game
k = 0
while True:
    print_board(board)
    k+=1
    print("Move ",k,": ")
    print("You are at: ", board[marker.x][marker.y])
    d = int(input("Enter Direction(0-7): "))
    marker = move_marker(board,marker,d)
    if(goal.x == marker.x and goal.y == marker.y):
        print("Game Over!")
        break